### ISSUE TITLE
ETA to release the next version including the FileSink change

### ISSUE THREAD

**Issue by cchacin** [ArpNetworking/metrics-codahale-extra#18]
Hi, I noticed that the `master` branch has already the change removing the old `TsdLogSink` in favor of the new `FileSink`

8cc7877a6730e37ddcbd14bd6f1a45dda430cb53

Any ETA to release that change?

Thanks.

**Comment by cchacin** [comment]
@BrandonArp @vjkoskela Am I right on this missing release?

**Comment by vjkoskela** [comment]
Yes, I believe you are correct. I just kicked off the release of 0.7.0 of all the packages in this project. Sorry for the delay. Feel free to reopen if you have any additional questions/concerns.

**Comment by cchacin** [comment]
@vjkoskela thanks 👍
